print("Esta es su calculadora")
print("Ingrese su primer numero:")
num=int(input())
print("Ingrese su segundo numero:")
num2=int(input())

print("La suma de ambos numeros es:"+ str(num + num2))
print("La diferencia de los numeros es: "+ str(num-num2))
print("La división de los mismos es :"+ str(num/num2))
print("Su multiplicación es :"+ str(num*num2))
